version: '3.8'
services:
    eadm:
        image: 'redgreat/wahoo:latest'
        container_name: wahoo
        restart: unless-stopped
        ports:
            - '8080:8090'
        volumes:
            - ./docker/db.config:/opt/wahoo/config/db.config
            - ./docker/sys.config.src.src:/opt/wahoo/config/sys.config.src.src
            - ./docker/vm.args.src:/opt/wahoo/config/vm.args.src
            - ./logs/:/opt/wahoo/log/:rw
        environment:
            DISABLE_IPV6: 'true'
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 500M
        mem_swappiness: 0
        oom_kill_disable: true
